@startuml

package "eventUpdateCmdPattern" {
  class Command {
    +executeClass: any
    +undo: any
    +value: any
    +Command(executeClass: any, undo: any, value: any)
  }
}

package "optimisticEventDataUpdateForNormal" {
  class OptimisticEventDataUpdateForNormal {
    +optimisticEventData(updateReqOption: optimisticEventDataUpdateForTimeEventParam): void
    +validation(): void
  }
}

class PostOthers {
  +result: any
  +reqParam: any
  +PostOthers(reqParam: any)
  +optimisticEventDataUpdate(updateReqOption: optimisticEventDataUpdateForTimeEventParam): void
  +_validation(updateReqOption: optimisticEventDataUpdateForTimeEventParam): void
  +updateLogic(updateReqOption: optimisticEventDataUpdateForTimeEventParam): void
  +getResult(): any
}

PostOthers --> OptimisticEventDataUpdateForNormal : extends

class PostOthersCommand {
  +command: any
  +executeInst: any
  +PostOthersCommand(value: any)
  +execute(): void
  +getResult(): any
}
note left: PostOthersCommand에서 \nCommand, PostOthers Class를 사용


PostOthersCommand --> Command : uses
PostOthersCommand --> PostOthers : uses

class EventUpdate {
  +current: any
  +commands: any[]
  +action(command: any): void
  +execute(command: any): void
  -verifyOptimisticUpdate(command: any): void
  -getWaveformIndexes(filterBeatsNEctopicList: any): void
  -getMergeBeatsNEctopicList(filterBeatsNEctopicList: any): void
  +undo(): void
  +getCurrentValue(): void
  +getResult(): void
}
note left: EventUpdate에서 \nCommand Class를 사용

EventUpdate --> Command : uses

@enduml