@startuml
skinparam rectangle {
  BorderColor black
  BorderThickness 1
  shape rectangle
}


caption 순열(permutation) 다이어 그램입니다. \n '123'숫자를 가지고 있는 모든 경우의 숫자를 만들어 냅니다.

rectangle "{1,2,3}" as C1 {
  rectangle "S(0,2), i=<u>2</u>" as C2_3 {
    rectangle "S(1,2), i=<u>2</u>" as C2_3_2 {
      rectangle "S(2,2)" as C2_3_2_1 {
      }
    }
    rectangle "S(1,2), i=<u>1</u>" as C2_3_1 {
      rectangle "S(2,2)" as C2_3_1_1
    }
  }

  rectangle "S(0,2), i=<u>1</u>" as C2_2 {
    rectangle "S(1,2), i=<u>2</u>" as C2_2_2 {
      rectangle "S(2,2)" as C2_2_2_1
    }

    rectangle "S(1,2), i=<u>1</u>" as C2_2_1 {
      rectangle "S(2,2)" as C2_2_1_1
    }
  }
  
  rectangle "S(0,2), i=<u>0</u>" as C2_1 {
    rectangle "S(<u>1</u>,2), i=<u>2</u>" as C2_1_2 {
      ' label bottom "This is a group of rectangles with value 3_"
      rectangle "S(2,2)" as C2_1_2_1
    }
    
    rectangle "S(<u>1</u>,2), i=<u>1</u>" as C2_1_1 {
      rectangle "S(2,2)" as C2_1_1_1
    }
  }
}

C1 -> C2_1
C2_1 -> C2_1_1
C2_1_1 -> C2_1_1_1
C2_1_1_1 -> C2_1_2
C2_1_2 -> C2_1_2_1
C2_1_2_1 -> C2_2

C2_2 -> C2_2_1
C2_2_1 -> C2_2_1_1
C2_2_1_1 -> C2_2_2
C2_2_2 -> C2_2_2_1
C2_2_2_1 -> C2_3

C2_3 -> C2_3_1
C2_3_1 -> C2_3_1_1
C2_3_1_1 -> C2_3_2
C2_3_2 -> C2_3_2_1

@enduml

